### ISSUE TITLE
Feed of all feeds

### ISSUE THREAD

**Issue by pbek** [azu/github-search-rss#6]
Thank you for this great tool. I use it to monitor PRs on https://github.com/NixOS/nixpkgs. 😁 

I wonder if there is a way to get a feed of all feed, so that I don't have to add all feeds to my feed reader, that can't reed OPML (Nextcloud News).

**Comment by azu** [comment]
It looks like Nextcloud News support opml import.
https://github.com/nextcloud/news-android/issues/780
opml import is a one-time import, but could be substituted for opml subscription.

**Comment by pbek** [comment]
Unfortunately the import doesn't work with the generated OPML file.

I get this:

![image](https://github.com/azu/github-search-rss/assets/1798101/f1c7f9af-ae01-4e31-bbd2-e8802b93ea2a)

...when I import:

```xml
<?xml version="1.0" encoding="UTF-8"?><opml version="2.0">
    <head>
    <title>GitHub Search Subscriptions</title>
    <dateCreated>2023-05-28T07:15:34.336Z</dateCreated>
</head>
    <body>
    <outline title="Subscriptions">
        <outline>
            <outline type="rss" title="microsoft/TypeScript Iteration Plan" htmlUrl="https://pbek.github.io/github-search-rss/nixos-smartgithg.json" xmlUrl="https://pbek.github.io/github-search-rss/nixos-smartgithg.json"/>
        </outline>
    </outline>
</body>
</opml>
```

Plus, you would need to import it new every time something changes, and the import only works with local files.

**Comment by azu** [comment]
> valid JSON

Nextcloud News uses opml.json?
Current opml file is xml.

- http://opml.org/spec2.opml

> you would need to import it new every time something changes,

Yes. The solution to the underlying problem would be a Feature Request to Nextcloud News.

As workaround, you can generate merged rss feed instead of opml index file.
However, I am not keen on this method as it limits the number of items in a single feed.

📝 create feeds for each search results currently
https://github.com/azu/github-search-rss/blob/4922905f0eec8e5e74e2469d2ac396a6f80d8658/src/index.ts#L238-L256
Instead of it, merge all results and create a single rss feed.

Pseudo code:

```json
// get all search results
const allItems = [];
for (const item of SEARCH_ITEMS) {
    const { query, TYPE, SIZE } = item;
    const items = await search({
        query,
        TYPE,
        GITHUB_TOKEN: GITHUB_TOKEN,
        SIZE: SIZE ?? 20
    });
    if (!items) {
        throw new Error("Can not search:" + query);
    }
    allItems.push(...items);
}
// generate merged rss
const rss = generateRSS(allItems, {
    title: "merged rss",
    link: `${BASE_URL}/all.json`,
    description: `merged rss on GitHub`,
    updated: new Date()
});
await fs.writeFile(path.join(distDir, "all.json"), rss, "utf-8");
```

**Comment by pbek** [comment]
That was what I'm looking for, thank you very much!
